# Generated by Django 5.0.2 on 2024-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('MEDIUM', 'medium'), ('LOW', 'low'), ('HIGH', 'high')], default='LOW', max_length=6),
        ),
    ]
