# Generated by Django 5.0.2 on 2024-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('MEDIUM', 'medium'), ('HIGH', 'high'), ('LOW', 'low')], default='LOW', max_length=6),
        ),
    ]
