# Generated by Django 5.0.2 on 2024-02-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_priority'),
        ('tasks', '0008_alter_task_due_date'),
    ]

    operations = [
    ]
