# Generated by Django 5.0.2 on 2024-02-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_merge_20240221_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('HIGH', 'high'), ('MEDIUM', 'medium')], default='LOW', max_length=6),
        ),
    ]
